# Generated by Django 4.2 on 2025-04-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VanGo', max_length=100, verbose_name='Nome do Site')),
                ('site_description', models.TextField(blank=True, verbose_name='Descrição do Site')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de Contato')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL do Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL do Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='URL do Twitter')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('passenger_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Percentual de Taxa para Passageiros (%)')),
                ('driver_fee_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Percentual de Taxa para Motoristas (%)')),
                ('cancellation_policy', models.TextField(blank=True, verbose_name='Política de Cancelamento')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Termos e Condições')),
                ('privacy_policy', models.TextField(blank=True, verbose_name='Política de Privacidade')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='core/', verbose_name='Favicon')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('answer', models.TextField(verbose_name='Resposta')),
                ('category', models.CharField(choices=[('general', 'Geral'), ('booking', 'Reservas'), ('payment', 'Pagamentos'), ('routes', 'Rotas'), ('drivers', 'Motoristas')], default='general', max_length=20, verbose_name='Categoria')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
                'ordering': ['category', 'order'],
            },
        ),
    ]
