# Generated by Django 4.2 on 2025-04-24 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('airport_transfer', 'Transfer Aeroporto'), ('city_tour', 'City Tour'), ('intercity', 'Intermunicipal'), ('custom', 'Personalizada')], max_length=20, verbose_name='Tipo de Rota')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('origin', models.CharField(max_length=100, verbose_name='Origem')),
                ('destination', models.CharField(max_length=100, verbose_name='Destino')),
                ('origin_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude de Origem')),
                ('origin_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude de Origem')),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude de Destino')),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude de Destino')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Distância (km)')),
                ('duration', models.PositiveIntegerField(verbose_name='Duração (minutos)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço por pessoa (R$)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Duração (minutos)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route', verbose_name='Rota')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RouteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('departure_time', models.TimeField(verbose_name='Horário de Partida')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='routes.route', verbose_name='Rota')),
            ],
            options={
                'verbose_name': 'Horário de Rota',
                'verbose_name_plural': 'Horários de Rota',
                'ordering': ['weekday', 'departure_time'],
                'unique_together': {('route', 'weekday', 'departure_time')},
            },
        ),
    ]
