# Generated by Django 4.2 on 2025-04-24 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('van', 'Van'), ('minibus', 'Micro-ônibus'), ('executive', 'Van Executiva')], default='van', max_length=10, verbose_name='Tipo de Veículo')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('license_plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidade de Passageiros')),
                ('has_air_conditioning', models.BooleanField(default=True, verbose_name='Ar Condicionado')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('has_usb_ports', models.BooleanField(default=False, verbose_name='Portas USB')),
                ('has_tv', models.BooleanField(default=False, verbose_name='TV')),
                ('has_accessibility', models.BooleanField(default=False, verbose_name='Acessibilidade')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/', verbose_name='Imagem Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Legenda')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Imagem do Veículo',
                'verbose_name_plural': 'Imagens do Veículo',
            },
        ),
    ]
