# Generated by Django 4.2 on 2025-04-24 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Data da Viagem')),
                ('num_passengers', models.PositiveIntegerField(default=1, verbose_name='Número de Passageiros')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Total (R$)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Concluída')], default='pending', max_length=10, verbose_name='Status')),
                ('booking_reference', models.CharField(max_length=10, unique=True, verbose_name='Referência da Reserva')),
                ('special_requests', models.TextField(blank=True, verbose_name='Solicitações Especiais')),
                ('pickup_location', models.CharField(blank=True, max_length=255, verbose_name='Local de Embarque')),
                ('dropoff_location', models.CharField(blank=True, max_length=255, verbose_name='Local de Desembarque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Passageiro')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='routes.route', verbose_name='Rota')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='routes.routeschedule', verbose_name='Horário')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-booking_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor (R$)')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('pix', 'PIX'), ('bank_transfer', 'Transferência Bancária'), ('cash', 'Dinheiro')], max_length=15, verbose_name='Método de Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('refunded', 'Reembolsado')], default='pending', max_length=10, verbose_name='Status')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Transação')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
